name: Flutter CI/CD

# 트리거 조건
on:
  push:
    #paths:
    #  - 'portfolio/**'  # 특정 프로젝트 폴더에서 변경 시에만 트리거
    branches: [ Development ]
  pull_request:
    paths:
      - 'portfolio/**'
    branches: [ Development ]

jobs:
  # CI
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest
    
    # 작업 수행 디렉토리 지정
    defaults:
      run:
        working-directory: portfolio

    steps:
    # 코드 체크아웃
    - uses: actions/checkout@v3
    
    # Flutter 환경 설정
    - name: Flutter 환경 설정
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
    
    # Flutter 버전 확인 (디버깅용)
    - name: Flutter 버전 확인
      run: flutter --version

    # 의존성 설치
    - name: 의존성 다운로드
      run: flutter pub get
    
    # 코드 정적 분석
    - name: 코드 분석
      run: dart analyze lib
    
    # 포맷팅 검사
    - name: 코드 포맷팅 검사
      run: dart format --set-exit-if-changed lib || true
    
    # 테스트 실행
#    - name: 단위 테스트 실행
#      run: flutter test
    
    # 웹 빌드 - HTML
    - name: 웹 빌드 - HTML
      run: flutter build web \
            --web-renderer html \
            --release \
            --base-href "/html/" \
            -o build-html

    # 웹 빌드 - CanvasKit
    - name: Build Web - CanvasKit 
      run: flutter build web \
            --web-renderer canvaskit \
            --release \
            --base-href "/canvaskit/" \
            -o build-canvaskit
    
    # 빌드 결과 병합
    - name: Merge builds
      run: |
        rm -rf web-dist
        mkdir -p web-dist/html web-dist/canvaskit
        mv build-html/* web-dist/html/
        mv build-canvaskit/* web-dist/canvaskit/

    # 아티팩트 업로드 (선택적)
    - uses: actions/upload-artifact@v4
      with:
        name: web-dist
        path: ../web-dist

  # CD - Github Pages 
  deploy:
    needs: build  # build 작업 성공 후 실행
    runs-on: ubuntu-latest
    
    steps:
    # 빌드된 아티팩트 다운로드
    - uses: actions/download-artifact@v4
      with:
        name: web-dist
        path: ./web-dist 
    
    # GitHub Pages 배포
    - name: GitHub Pages 배포
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
        publish_dir: ./web-dist  # 다운로드한 아티팩트 경로 ./build/web에서 변경
